### ISSUE TITLE
inconsistent constant pool data

### ISSUE THREAD

**Issue by LegendaryGeek** [ldtteam/Structurize#399]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- Structurize Version: structurize-0.13.191-alpha even tho the jar is not found in the file manager
- MineColonies Version (if related bug): not certain
- Related Mods and their Versions:
here is my pack since aparently alot is wrong and wonky, on version 0.5 for this issue: https://www.curseforge.com/minecraft/modpacks/kenzco-pack-for-friendos

## Expected behavior

the server load

## Actual behavior

the server says structurize has an inconsistant constant pool data

## Steps to reproduce the issue

1.  load (to my knowledge) my modpack linked above on a server
2.  wait for it to load
3. observe the console as it crashes

### Logs

- latest.log: https://gist.github.com/LegendaryGeek/964ccb71fa2d544b1fb4e0b7c041602a
- crashlog: https://gist.github.com/LegendaryGeek/24d00895ef137c402af61ec1226a6d57

### Notes

neither minecolonies, nor structurize appears in my modlist, 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ZRunner** [comment]
I got the same crash reason, but in a singleplayer world. FYI it happened just after sleeping, when I "woke up" from my bed. And now I cannot access my world again (crashes when I load it, right after the 100%, so I guess it's something about rendering?).
I'm reposting my logs here because they appear to be slightly different and might help (or I'm just blind, it happens lol)

## Context
* Minecraft Version: 1.16.5
* Structurize Version: structurize-0.13.197-alpha
* MineColonies Version: minecolonies-0.14.259-ALPHA
* Forge version: 36.1.25
* Related Mods and their Versions: see client logs

## Logs
* latest.log: https://paste.ee/p/YJav4
* crash server: https://paste.ee/p/xRjwF
* crash client: https://paste.ee/p/BDczX

**Comment by Nightenom** [comment]
@Raycoms same as before at: https://github.com/ldtteam/Structurize/blob/d73daa292aa76984762d66830d8a7327e30eafed/src/main/java/com/ldtteam/structurize/blocks/interfaces/IBlueprintDataProvider.java#L261
Might be worth checking all ifaces for lambdas

**Comment by Raycoms** [comment]
That fine?
