### ISSUE TITLE
Config keys are not translated properly

### ISSUE THREAD

**Issue by someaddons** [ldtteam/Structurize#405]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- Structurize Version:
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Expected behavior

Config keys are translated properly
## Actual behavior

Config keys are not translated properly

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Really weird, there aren't any significant changes around AbstractConfiguration or LanguageHandler, so:
If all then I blame mojmap commit
If StringValue only then I blame Forge or Ray :P

**Comment by someaddons** [comment]
none of them seem to be translated^^

**Comment by uecasm** [comment]
They get translated (to english) if you delete your existing config file and let it be re-created.  Apparently a change in comment text is not sufficient for it to self-correct.  I don't think the comments are intended to ever be translated to not-english though, since translations are client-side-only.  It might be better to not even try to translate them, it doesn't look like the library intended them to be.  (There is a translation key but it's for the GUI text, when something does provide a config GUI.)

**Comment by Nightenom** [comment]
Reopen if persists
