### ISSUE TITLE
Custom Schematics not showing up

### ISSUE THREAD

**Issue by FaeTech** [ldtteam/Structurize#454]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.219

## Problem description
 I'm trying to create a custom village, an the schematics I've created aren't showing up in the build gui in game. I have the proper hut block necessary, and no external mods are used in the schematic blueprint. I've watched the YouTube tutorial as well as read extensively through the schematic wiki page and I've essentially done everything correctly. I'm assuming this is a bug but I would really like this to be fixed

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
There isn't any useful information in this report.  If you're going to report this sort of thing here, you need the exact reproduction steps or otherwise sufficient demonstration that it's actually a bug.

Otherwise, please join the Discord server and ask in the #schem-help channel there for help creating your custom style.  Many people have done this so it does work, it's likely just that there is some step you are missing -- which is not a bug.
