### ISSUE TITLE
Copper framed blocks replaced for free

### ISSUE THREAD

**Issue by JerryTC1** [ldtteam/Structurize#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-10.491-alpha

### MineColonies Version (if related bug)

1.19.2-10.405

### Related Mods and their Versions

1. 43.2.0 Forge
2. no idea what you mean by block UI mod, JEI's version is 11.6.0.1105
3. 1.19-1.0.83 ALPHA

### Current Behavior

When building in the steampunk style, builders will replace any framed copper blocks with exposed (or more eroded copper types) framed blocks for entirely free, as long as the block was previously placed down before

they will not request these blocks

i can confirm this because i did not make exposed copper framed blocks, yet they were placed at my builders hut

### Expected Behavior

the builder would request exposed copper framed blocks, and use them to replace the old blocks

### Reproduction Steps

Make any building that uses framed copper blocks
Supply it with the needed materials (dont use creative quick build)
let the builder make it normally
repeat this until the building is at a level it requires framed exposed copper blocks
upgrade it, but do not give the builder any exposed copper framed blocks
wait and watch

### Logs

N/A

### Anything else?

![2023-05-12_01 13 16](https://github.com/ldtteam/Structurize/assets/133319568/03a97e7f-8e49-46c7-bada-3c122b1b5943)

example of what i mean by framed copper and framed exposed blocks

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
For reasons (mostly good ones, to avoid accidentally destroying important state from unknown other mods), builders won't replace a block if it's the same block type but has different NBT data.  Due to how DO works, this means they will not replace any framed blocks that only change materials, though they will replace blocks that change framing style.  Currently, these sorts of things are considered schematic bugs -- i.e. you should ask the designer of Steampunk to make the block changes more significant between levels.  Or perhaps they intended this effect.

**Comment by MotionlessTrain** [comment]
We didn't. I at least didn't know structurize did this, and it is intentional/unavoidable

**Comment by MotionlessTrain** [comment]
So if I understand correctly, we cannot use any framed blocks there at other levels, except when we change the frame style? (i.e. just a change of the outer material is not  enough)

**Comment by uecasm** [comment]
Yes.  Turn advanced tooltips on and look at the block id -- if it changes, then the builder will replace it on upgrade.  If it's the same, then they won't.  `domum_ornamentum:double_crossed` is a different block type from `domum_ornamentum:up_gated` (two different framing styles), but two double-crossed frames with different materials are the same type, so the first will be replaced and the second will not.

Even blockstate changes usually don't matter, which is why there have been reports of builders not changing a right-side-up stair to an upside-down stair, because it was the same block type in the same location.  (Though in the case of vanilla stairs and almost anything non-DO, different materials are different block ids, so they will trigger replacement.)

Whether or not some part of this is not intended and should be fixed, I don't know (which is why I've left this open for the lead devs to ponder), but this is how things work at present, and changing it too broadly could be dangerous.

Though it occurs to me that I've probably made the same mistake in 9x9, so there's probably some unintended free upgrades there too.

**Comment by MotionlessTrain** [comment]
There are probably several styles with free shingle upgrades too, yeah

This might be exploited to get some DO blocks which were meant to be harder to get, by making an upgradeable decoration, if someone knows about this behaviour. Not that I think that is a huge issue, as you can't turn DO blocks back into their materials, but it still seems an unintended side-effect
