### ISSUE TITLE
Structurize calling incorrect deco schematic on upgrade

### ISSUE THREAD

**Issue by Moobien** [ldtteam/Structurize#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

6662 Beta

### MineColonies Version (if related bug)

343 Beta

### Current Behavior

Upgrading fortress road corner 1 instead builds fortress wall corner 2

### Expected Behavior

upgrading corner 1 to corner 2

### Reproduction Steps

use the versions specified.
Have a builder build fortress/roads/corner1
then have the builder upgrade that deco and they will instead build fortress/walls/corner2

I SUSPECT the issue lies in the 2 schematics having the same name but in different folders. instead of grabbing the lvl 2 schematic from roads, it seems to be pulling the schematic with the same name from walls instead.

### Logs

n/a

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It is an issue with how the compatibility between old decoration controllers (1.18-) and new ones work. As the old ones don't know about where they were in the build tool now (they still have the old path from before the rework), they search in the style for the first decoration which happens to have the same name. In case of fortress, both walls and roads are named "corner", which means one of them will find the wrong one instead of the same decoration

**Comment by Raycoms** [comment]
So, a minecolonies schematic issue.
